### ISSUE TITLE
i'm sorry to make an issue but

### ISSUE THREAD

**Issue by fnfporterhi** [SanicBTW/Funkin-Engine#2]
https://github.com/fnfporterhi/update

please read

**Comment by SanicBTW** [comment]
Couldn't you make the fucking issue in another repo except this one 💀?

**Comment by SanicBTW** [comment]
Anyways, I'm glad you still alive bro I thought some bad shit happened

**Comment by fnfporterhi** [comment]
lol and sorry this was the latest one

**Comment by fnfporterhi** [comment]
hey sanic. i saw you were retiring. it was a good run playing all your ports and seeing them in action. glad i got to be a part of it.

**Comment by SanicBTW** [comment]
Thanks for the support, I think I would retire only from FNF and keep doing my stuff, since it's what gives me more burnouts but I still don't know, I will keep you updated in a change of mind.

But I'm sure I want to finish most of my shit before that so yeah.
